version: '3'

services:
  #Base Dependencies
  cassandra:
    image: scylladb/scylla
    ports:
      - 9042:9042

  kafka:
    image: spotify/kafka
    ports:
      - 9092:9092

  nats:
    image: nats-streaming
    ports:
      - 4222:4222

  #Service
  todo-service:
    image: benniekrijger/todo-service-go
    ports:
      - 8080:8080
    links:
      - "cassandra:cassandra"
      - "nats:nats"
    environment:
      CASSANDRA_URL: cassandra:9042
      NATS_URL: nats://nats:4222
