// Code generated by protoc-gen-go.
// source: events/todo_events.proto
// DO NOT EDIT!

/*
Package events is a generated protocol buffer package.

It is generated from these files:
	events/todo_events.proto

It has these top-level messages:
	TodoAdded
	TodoRemoved
	TodoPublishTriggered
*/
package events

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TodoAdded struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Completed bool   `protobuf:"varint,3,opt,name=completed" json:"completed,omitempty"`
}

func (m *TodoAdded) Reset()                    { *m = TodoAdded{} }
func (m *TodoAdded) String() string            { return proto.CompactTextString(m) }
func (*TodoAdded) ProtoMessage()               {}
func (*TodoAdded) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TodoAdded) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TodoAdded) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TodoAdded) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type TodoRemoved struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *TodoRemoved) Reset()                    { *m = TodoRemoved{} }
func (m *TodoRemoved) String() string            { return proto.CompactTextString(m) }
func (*TodoRemoved) ProtoMessage()               {}
func (*TodoRemoved) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TodoRemoved) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TodoPublishTriggered struct {
	OffsetId string `protobuf:"bytes,1,opt,name=offsetId" json:"offsetId,omitempty"`
	Limit    string `protobuf:"bytes,2,opt,name=limit" json:"limit,omitempty"`
}

func (m *TodoPublishTriggered) Reset()                    { *m = TodoPublishTriggered{} }
func (m *TodoPublishTriggered) String() string            { return proto.CompactTextString(m) }
func (*TodoPublishTriggered) ProtoMessage()               {}
func (*TodoPublishTriggered) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TodoPublishTriggered) GetOffsetId() string {
	if m != nil {
		return m.OffsetId
	}
	return ""
}

func (m *TodoPublishTriggered) GetLimit() string {
	if m != nil {
		return m.Limit
	}
	return ""
}

func init() {
	proto.RegisterType((*TodoAdded)(nil), "events.TodoAdded")
	proto.RegisterType((*TodoRemoved)(nil), "events.TodoRemoved")
	proto.RegisterType((*TodoPublishTriggered)(nil), "events.TodoPublishTriggered")
}

func init() { proto.RegisterFile("events/todo_events.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0xc1, 0xaa, 0x82, 0x50,
	0x10, 0x86, 0xd1, 0xcb, 0x15, 0x9d, 0x0b, 0x77, 0x71, 0x70, 0x71, 0x88, 0x02, 0x71, 0xe5, 0xaa,
	0x16, 0x3d, 0x41, 0xbb, 0x5a, 0x15, 0xe2, 0x3e, 0xb0, 0x19, 0x6d, 0xe0, 0xd8, 0x88, 0x4e, 0x3e,
	0x7f, 0xa8, 0x58, 0x8b, 0x76, 0xf3, 0xfd, 0x33, 0xfc, 0x7c, 0x03, 0x96, 0x06, 0x7a, 0x68, 0xbf,
	0x53, 0x41, 0xb9, 0xce, 0xf3, 0xb6, 0xed, 0x44, 0xc5, 0x04, 0x33, 0xa5, 0x67, 0x88, 0x0a, 0x41,
	0x39, 0x20, 0x12, 0x9a, 0x7f, 0xf0, 0x19, 0xad, 0x97, 0x78, 0x59, 0x94, 0xfb, 0x8c, 0x26, 0x86,
	0x5f, 0x65, 0x75, 0x64, 0xfd, 0x29, 0x9a, 0xc1, 0xac, 0x21, 0xba, 0x49, 0xd3, 0x3a, 0x52, 0x42,
	0xfb, 0x93, 0x78, 0x59, 0x98, 0x7f, 0x82, 0x74, 0x03, 0x7f, 0x63, 0x61, 0x4e, 0x8d, 0x0c, 0xdf,
	0x95, 0xe9, 0x11, 0xe2, 0x71, 0x7d, 0x79, 0x96, 0x8e, 0xfb, 0x7b, 0xd1, 0x71, 0x5d, 0x53, 0x47,
	0x68, 0x56, 0x10, 0x4a, 0x55, 0xf5, 0xa4, 0xa7, 0xe5, 0xfa, 0xcd, 0xa3, 0x86, 0xe3, 0x86, 0x75,
	0xd1, 0x98, 0xa0, 0x0c, 0xa6, 0x47, 0xf6, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x60, 0x84, 0xfe,
	0xa5, 0xe4, 0x00, 0x00, 0x00,
}
