// Code generated by protoc-gen-go.
// source: TodoEvents.proto
// DO NOT EDIT!

/*
Package events is a generated protocol buffer package.

It is generated from these files:
	TodoEvents.proto

It has these top-level messages:
	TodoAdded
*/
package events

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TodoAdded struct {
	Title            *string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Completed        *bool   `protobuf:"varint,2,opt,name=completed" json:"completed,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TodoAdded) Reset()                    { *m = TodoAdded{} }
func (m *TodoAdded) String() string            { return proto.CompactTextString(m) }
func (*TodoAdded) ProtoMessage()               {}
func (*TodoAdded) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TodoAdded) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *TodoAdded) GetCompleted() bool {
	if m != nil && m.Completed != nil {
		return *m.Completed
	}
	return false
}

func init() {
	proto.RegisterType((*TodoAdded)(nil), "events.TodoAdded")
}

func init() { proto.RegisterFile("TodoEvents.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 101 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x08, 0xc9, 0x4f, 0xc9,
	0x77, 0x2d, 0x4b, 0xcd, 0x2b, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0x05,
	0xf3, 0x94, 0xec, 0xb9, 0x38, 0x41, 0x72, 0x8e, 0x29, 0x29, 0xa9, 0x29, 0x42, 0x22, 0x5c, 0xac,
	0x25, 0x99, 0x25, 0x39, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x90, 0x0c,
	0x17, 0x67, 0x72, 0x7e, 0x6e, 0x41, 0x4e, 0x6a, 0x49, 0x6a, 0x8a, 0x04, 0x93, 0x02, 0xa3, 0x06,
	0x47, 0x10, 0x42, 0xc0, 0x89, 0xc9, 0x83, 0x11, 0x10, 0x00, 0x00, 0xff, 0xff, 0x06, 0x44, 0xaf,
	0x5c, 0x5f, 0x00, 0x00, 0x00,
}
